"""Add Name

Revision ID: 0f81b57b7384
Revises: 9288c381c02d
Create Date: 2020-07-07 02:37:24.964187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f81b57b7384'
down_revision = '9288c381c02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cred', sa.Column('cred_validity', sa.String(length=128), nullable=True))
    op.drop_column('did', 'cred_validity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('did', sa.Column('cred_validity', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('cred', 'cred_validity')
    # ### end Alembic commands ###
