"""Add Encrypted

Revision ID: 5f306060b731
Revises: c2a352254648
Create Date: 2020-07-06 21:03:40.395444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f306060b731'
down_revision = 'c2a352254648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cred', sa.Column('cred_encrypted', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cred', 'cred_encrypted')
    # ### end Alembic commands ###
