"""Add Name

Revision ID: 9288c381c02d
Revises: a775bd26132e
Create Date: 2020-07-07 02:37:01.489327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9288c381c02d'
down_revision = 'a775bd26132e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('did', sa.Column('cred_validity', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('did', 'cred_validity')
    # ### end Alembic commands ###
